In [1]:
# --- importacion de librerias ---#

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# --- cargar archivos ---#

df = pd.read_csv('GoogleAds_DataAnalytics_Sales_Uncleaned.csv')

In [3]:
# --- exploracion de datos ---#

df.head(n=10)

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,DataAnalyticsCourse,104.0,4498.0,$231.88,14.0,7.0,0.058,$1892,2024-11-16,hyderabad,desktop,learn data analytics
1,A1001,DataAnalyticsCourse,173.0,5107.0,$216.84,10.0,8.0,0.046,$1679,20-11-2024,hyderabad,mobile,data analytics course
2,A1002,Data Anlytics Corse,90.0,4544.0,$203.66,26.0,9.0,NaN,$1624,2024/11/16,hyderabad,Desktop,data analitics online
3,A1003,Data Analytcis Course,142.0,3185.0,$237.66,17.0,6.0,NaN,$1225,2024-11-26,HYDERABAD,tablet,data anaytics training
4,A1004,Data Analytics Corse,156.0,3361.0,$195.9,30.0,8.0,NaN,$1091,2024-11-22,hyderabad,desktop,online data analytic
5,A1005,DataAnalyticsCourse,195.0,3776.0,$243.57,10.0,8.0,NaN,$1315,16-11-2024,hyderabad,MOBILE,data anaytics training
6,A1006,Data Analytics Corse,116.0,4480.0,$237.79,17.0,5.0,0.043,$1640,06-11-2024,hyderabad,TABLET,data analytics course
7,A1007,Data Analytics Corse,184.0,5060.0,$229.61,23.0,3.0,0.016,$1509,2024/11/24,Hyderbad,TABLET,analytics for data
8,A1008,Data Analytics Corse,113.0,5434.0,NaN,27.0,4.0,0.058,$1362,2024/11/24,Hyderbad,Tablet,data anaytics training
9,A1009,Data Analytcis Course,166.0,3355.0,$186.78,24.0,9.0,0.054,$1029,2024/11/12,Hyderbad,Mobile,online data analytic

In [4]:
df.tail(n=10)

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Conversion Rate,Sale_Amount,Ad_Date,Location,Device,Keyword
2590,A3590,Data Analytcis Course,136.0,3036.0,$201.48,20.0,7.0,0.046,$1811,2024/11/13,hydrebad,Tablet,data anaytics training
2591,A3591,DataAnalyticsCourse,146.0,5743.0,$190.39,18.0,3.0,0.021,$1108,13-11-2024,hyderabad,mobile,data anaytics training
2592,A3592,Data Analytics Corse,152.0,5061.0,$234.42,12.0,5.0,NaN,$1566,10-11-2024,Hyderbad,tablet,online data analytic
2593,A3593,Data Analytics Corse,189.0,5944.0,$202.89,28.0,5.0,NaN,$1360,08-11-2024,HYDERABAD,MOBILE,data analytics course
2594,A3594,Data Anlytics Corse,99.0,4446.0,$233.53,11.0,6.0,0.061,$1189,2024/11/05,hyderabad,Tablet,data anaytics training
2595,A3595,DataAnalyticsCourse,88.0,5344.0,$242.07,17.0,9.0,0.054,$1418,29-11-2024,HYDERABAD,MOBILE,online data analytic
2596,A3596,DataAnalyticsCourse,154.0,3211.0,$248.28,14.0,6.0,0.039,$1950,2024/11/28,hyderabad,TABLET,data analitics online
2597,A3597,Data Anlytics Corse,113.0,3808.0,$233.25,18.0,4.0,0.035,$1085,2024-11-02,Hyderbad,desktop,data anaytics training
2598,A3598,Data Analytics Corse,196.0,5853.0,$220.13,16.0,7.0,0.036,$1558,2024-11-08,hydrebad,Tablet,data anaytics training
2599,A3599,Data Analytics Corse,NaN,5453.0,NaN,12.0,5.0,NaN,$1174,2024/11/22,HYDERABAD,desktop,analytics for data

In [5]:
df.shape

(2600, 13)

In [6]:
# --- eliminar datos duplicados ---#

df.duplicated().sum()

0

In [7]:
# --- limpiar datos de tipo str ---#
df['Campaign_Name'].value_counts()

df['Campaign_Name'] = df['Campaign_Name'].replace({
    'Data Analytics Corse':'Data Analytcis Course',
    'DataAnalyticsCourse': 'Data Analytcis Course',
    'Data Anlytics Corse': 'Data Analytcis Course'
    })

df['Campaign_Name'].value_counts()

Data Analytcis Course    2600
Name: Campaign_Name, dtype: int64

In [8]:
df['Location'].value_counts()

df['Location'] = df['Location'].replace({
    'HYDERABAD':'Hyderabad',
    'hyderabad': 'Hyderabad',
    'Hyderbad': 'Hyderabad',
    'hydrebad': 'Hyderabad'
    })

df['Location'].value_counts()

Hyderabad    2600
Name: Location, dtype: int64

In [9]:
df['Device'].value_counts()

df['Device'] = df['Device'].replace({
    'MOBILE':'Mobile',
    'mobile': 'Mobile',
    'desktop':'Desktop',
    'DESKTOP':'Desktop',
    'TABLET':'Tablet',
    'tablet':'Tablet'
    })

df['Device'].value_counts()

Desktop    888
Mobile     878
Tablet     834
Name: Device, dtype: int64

In [10]:
df['Keyword'].value_counts()

df['Keyword'] = df['Keyword'].replace({
    'online data analytic':'data analytics online',
    'data analitics online':'data analytics online',
    'data anaytics training':'data analytics training'
})

df['Keyword'].value_counts()

data analytics online      873
learn data analytics       444
data analytics course      440
analytics for data         429
data analytics training    414
Name: Keyword, dtype: int64

In [11]:
#--- buscar datos nulos ---#

df.isna().sum()

Ad_ID                0
Campaign_Name        0
Clicks             112
Impressions         54
Cost                97
Leads               48
Conversions         74
Conversion Rate    626
Sale_Amount        139
Ad_Date              0
Location             0
Device               0
Keyword              0
dtype: int64

In [12]:
# esta columna es mejor recrearla en sql
df = df.drop(columns=['Conversion Rate'])

df.columns

Index(['Ad_ID', 'Campaign_Name', 'Clicks', 'Impressions', 'Cost', 'Leads',
       'Conversions', 'Sale_Amount', 'Ad_Date', 'Location', 'Device',
       'Keyword'],
      dtype='object')

In [13]:
df.head()

,Ad_ID,Campaign_Name,Clicks,Impressions,Cost,Leads,Conversions,Sale_Amount,Ad_Date,Location,Device,Keyword
0,A1000,Data Analytcis Course,104.0,4498.0,$231.88,14.0,7.0,$1892,2024-11-16,Hyderabad,Desktop,learn data analytics
1,A1001,Data Analytcis Course,173.0,5107.0,$216.84,10.0,8.0,$1679,20-11-2024,Hyderabad,Mobile,data analytics course
2,A1002,Data Analytcis Course,90.0,4544.0,$203.66,26.0,9.0,$1624,2024/11/16,Hyderabad,Desktop,data analytics online
3,A1003,Data Analytcis Course,142.0,3185.0,$237.66,17.0,6.0,$1225,2024-11-26,Hyderabad,Tablet,data analytics training
4,A1004,Data Analytcis Course,156.0,3361.0,$195.9,30.0,8.0,$1091,2024-11-22,Hyderabad,Desktop,data analytics online

In [14]:
mean_clicks = df['Clicks'].median()
df['Clicks'] = df['Clicks'].fillna(mean_clicks).round().astype(int)

df['Clicks'].tail(n=10)

2590    136
2591    146
2592    152
2593    189
2594     99
2595     88
2596    154
2597    113
2598    196
2599    139
Name: Clicks, dtype: int32

In [15]:
mean_clicks = df['Impressions'].median()
df['Impressions'] = df['Impressions'].fillna(mean_clicks).round().astype(int)

In [16]:
df.isna().sum()

Ad_ID              0
Campaign_Name      0
Clicks             0
Impressions        0
Cost              97
Leads             48
Conversions       74
Sale_Amount      139
Ad_Date            0
Location           0
Device             0
Keyword            0
dtype: int64

In [20]:
df['Cost'] = (
    df['Cost'].str.replace("$","", regex=False)
    )

mean_cost = df['Cost'].median()
df['Cost'] = df['Cost'].fillna(mean_cost).astype(float)

In [21]:
df.isna().sum()

Ad_ID              0
Campaign_Name      0
Clicks             0
Impressions        0
Cost               0
Leads             48
Conversions       74
Sale_Amount      139
Ad_Date            0
Location           0
Device             0
Keyword            0
dtype: int64

In [22]:
mean_leads = df['Leads'].median()
df['Leads'] = df['Leads'].fillna(mean_leads).round().astype(int)

In [23]:
mean_conversions = df['Conversions'].median()
df['Conversions'] = df['Conversions'].fillna(mean_conversions).round().astype(int)

In [24]:
df['Sale_Amount'] = (
    df['Sale_Amount'].str.replace("$","", regex=False)
    )

mean_sale_amount = df['Sale_Amount'].median()
df['Sale_Amount'] = df['Sale_Amount'].fillna(mean_sale_amount).astype(float)

In [25]:
df.isna().sum()

Ad_ID            0
Campaign_Name    0
Clicks           0
Impressions      0
Cost             0
Leads            0
Conversions      0
Sale_Amount      0
Ad_Date          0
Location         0
Device           0
Keyword          0
dtype: int64

In [32]:
df['Ad_Date'] = df['Ad_Date'].astype(str)

df['Ad_Date'] = df['Ad_Date'].str.replace('/','-', regex = False)

df['Ad_Date'] = pd.to_datetime(df['Ad_Date'], dayfirst= True, errors='coerce')

In [33]:
# --- exportar a sqlite ---#

import sqlite3

db_clean = "google_ads_sales_clean.db"

conn = sqlite3.connect(db_clean)

df.to_sql('ads_data_clean', conn, if_exists='replace', index=False)

conn.close()

In [39]:
y = df['Sale_Amount']

X_base = df.drop(columns=['Sale_Amount','Ad_Date', 'Ad_ID'])

X_encoded = pd.get_dummies(X_base, drop_first=True)

X_with_const = sm.add_constant(X_encoded)

model1 = sm.OLS(y, X_with_const)
results1 = model1.fit()

print(results1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            Sale_Amount   R-squared:                       0.004
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.8870
Date:                Tue, 30 Dec 2025   Prob (F-statistic):              0.553
Time:                        18:42:09   Log-Likelihood:                -18328.
No. Observations:                2600   AIC:                         3.668e+04
Df Residuals:                    2588   BIC:                         3.675e+04
Df Model:                          11
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                            1431.5655     75.140     19.052      0.000    1284.225    1578.906
Clicks                              0.2928      0.162      1.802      0.072      -0.026       0.611
Impressions                        -0.0024      0.006     -0.370      0.712      -0.015       0.010
Cost                                0.1321      0.276      0.478      0.633      -0.410       0.674
Leads                               0.4241      0.920      0.461      0.645      -1.380       2.228
Conversions                        -0.4518      2.448     -0.185      0.854      -5.253       4.349
Device_Mobile                      -4.6949     13.335     -0.352      0.725     -30.843      21.453
Device_Tablet                      -0.3539     13.494     -0.026      0.979     -26.813      26.105
Keyword_data analytics course      16.3884     19.000      0.863      0.388     -20.869      53.645
Keyword_data analytics online      -8.7476     16.497     -0.530      0.596     -41.096      23.600
Keyword_data analytics training     4.6049     19.292      0.239      0.811     -33.224      42.434
Keyword_learn data analytics       26.9860     18.954      1.424      0.155     -10.180      64.152
==============================================================================
Omnibus:                      788.559   Durbin-Watson:                   2.079
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              120.910
Skew:                          -0.022   Prob(JB):                     5.56e-27
Kurtosis:                       1.944   Cond. No.                     6.35e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.35e+04. This might indicate that there are
strong multicollinearity or other numerical problems.